package com.aurea.caonb.egizatullin.data;

import io.swagger.annotations.ApiModelProperty;
import java.util.List;

public class Repository {

    @ApiModelProperty(
       notes = "Autogenerated identifier")
    public final int id;
    @ApiModelProperty(required = true, example = "apache", notes = "Owner of github repository")
    public final String owner;
    @ApiModelProperty(required = true, example = "poi", notes = "Name of github repository")
    public final String repo;
    @ApiModelProperty(example = "table-borders", notes = "Default value will be obtained from repository", position = 1)
    public final String branch;
    @ApiModelProperty(dataType = "HEX", example = "925f4b85adbf04581fc309e2bcf1f6435edcf445", notes = "Default is last commit", position = 2)
    public final String commitHash;

    @ApiModelProperty(notes = "Change history", position = 3)
    public final List<RepositoryHistoryItem> history;

    public Repository(int id, String owner, String repo, String branch, String commitHash,
        List<RepositoryHistoryItem> history) {
        this.id = id;
        this.owner = owner;
        this.repo = repo;
        this.branch = branch;
        this.commitHash = commitHash;
        this.history = history;
    }
}
